name: my-first-workflow
on: 
  push:
    branches:
      - main  
jobs:
  action-demo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
      - name: Print Index.html file
        run: cat index.html
