name: my-first-workflow
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "Build Started"
      - name: Build Completed
        run: echo "Build Completed"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Testing Step
        run: echo "Testing Started"
      - name: Testing Completed
        run: echo "Testing Completed"
